### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Ade0408** [LennonChin/Code-Confuse-Plugin#2]
指定需要混淆的文件夹路径还有SDK以及输出文件夹之后, 运行脚本会报错
```
// 为了方便预览, 我分行显示出来
python3 Confuse.py \
-i /Users/xxx/Downloads/Code-Confuse-Plugin-master/Demo/project/file
-s /Users/xxx/Downloads/Code-Confuse-Plugin-master/Demo/System_Frameworks_iOS11 
-o /Users/xxx/Downloads/Code-Confuse-Plugin-master/temp
```
报错内容为:
```
Complete write System identifiers into Dict File
Start scanning assign Clean identifiers...
Traceback (most recent call last):
  File "Confuse.py", line 439, in <module>
    clean_identifiers = DealCleanIdentifers(clean_dirs).parse_clean_identifiers()
  File "Confuse.py", line 267, in parse_clean_identifiers
    clean_file_paths = ConfuseBiz.scan_path(self.clean_file_dirs, None, ['h', 'm'])
  File "Confuse.py", line 21, in scan_path
    for input_dir in input_dirs:
TypeError: 'NoneType' object is not iterable
```
请问这个问题怎么破呢?

**Comment by LennonChin** [comment]
检查一下使用的路径是不是对的呢？
根据异常的信息，可能是因为`-e`和`-c`参数没有传，项目里也没有对空参数做容错了，所以报错了。
可以尝试传一下`-e`和`-c`参数，只要是存在的路径，空目录也行。

**Comment by Ade0408** [comment]
很感谢你的回复，我在发现这个问题后根据你的代码自己重新写了一个混淆的。很感谢你提供的思路

**Comment by LennonChin** [comment]
OK，那这个问题我就直接关闭了。
